add linux arm build (#16)

diff --git a/.github/workflows/build-ffmpeg.yml b/.github/workflows/build-ffmpeg.yml
--- a/.github/workflows/build-ffmpeg.yml
+++ b/.github/workflows/build-ffmpeg.yml
@@ -24,40 +24,58 @@ jobs:
             arch: x86_64
             shell: bash
             cmake_generator: Unix Makefiles
-            ffmpeg_extras: |
-              --enable-amf \
-              --enable-cuda \
-              --enable-cuda_llvm \
-              --enable-encoder=h264_amf,hevc_amf \
-              --enable-encoder=h264_nvenc,hevc_nvenc \
-              --enable-encoder=h264_vaapi,hevc_vaapi \
-              --enable-ffnvcodec \
-              --enable-nvenc \
-              --enable-v4l2_m2m \
-              --enable-vaapi \
+            ffmpeg_extras: >-
+              --enable-amf
+              --enable-cuda
+              --enable-cuda_llvm
+              --enable-encoder=h264_amf,hevc_amf
+              --enable-encoder=h264_nvenc,hevc_nvenc
+              --enable-encoder=h264_vaapi,hevc_vaapi
+              --enable-ffnvcodec
+              --enable-nvenc
+              --enable-v4l2_m2m
+              --enable-vaapi
+              --enable-vdpau
+          - os_type: linux
+            os: ubuntu-22.04
+            arch: aarch64
+            shell: bash
+            cmake_generator: Unix Makefiles
+            host: aarch64-linux-gnu
+            ffmpeg_extras: >-
+              --enable-amf
+              --enable-cuda
+              --enable-cuda_llvm
+              --enable-encoder=h264_amf,hevc_amf
+              --enable-encoder=h264_nvenc,hevc_nvenc
+              --enable-encoder=h264_vaapi,hevc_vaapi
+              --enable-ffnvcodec
+              --enable-nvenc
+              --enable-v4l2_m2m
+              --enable-vaapi
               --enable-vdpau
           - os_type: macos
             os: macos-11
             arch: x86_64
             shell: bash
             cmake_generator: Unix Makefiles  # should be `Xcode` but that fails
-            ffmpeg_extras: |
-              --enable-encoder=h264_videotoolbox,hevc_videotoolbox \
+            ffmpeg_extras: >-
+              --enable-encoder=h264_videotoolbox,hevc_videotoolbox
               --enable-videotoolbox
           - os_type: windows
             os: windows-2022
             arch: x86_64
             shell: msys2 {0}
             cmake_generator: MSYS Makefiles
-            ffmpeg_extras: |
-              --enable-amf \
-              --enable-cuda \
-              --enable-d3d11va \
-              --enable-encoder=h264_amf,hevc_amf \
-              --enable-encoder=h264_mf,hevc_mf \
-              --enable-encoder=h264_nvenc,hevc_nvenc \
-              --enable-ffnvcodec \
-              --enable-nvenc \
+            ffmpeg_extras: >-
+              --enable-amf
+              --enable-cuda
+              --enable-d3d11va
+              --enable-encoder=h264_amf,hevc_amf
+              --enable-encoder=h264_mf,hevc_mf
+              --enable-encoder=h264_nvenc,hevc_nvenc
+              --enable-ffnvcodec
+              --enable-nvenc
               --enable-mediafoundation
     runs-on: ${{ matrix.os }}
     defaults:
@@ -79,6 +97,46 @@ jobs:
       - name: Setup Dependencies Unix
         if: ${{ matrix.os_type != 'windows' }}
         run: |
+          echo "::group::${{ matrix.os_type }} dependencies"
+          if [[ ${{ matrix.os }} == "ubuntu-18.04" ]]; then
+            dist="bionic"
+          elif [[ ${{ matrix.os }} == "ubuntu-20.04" ]]; then
+            dist="focal"
+          elif [[ ${{ matrix.os }} == "ubuntu-22.04" ]]; then
+            dist="jammy"
+          fi
+
+          package_arch="amd64"
+          if [[ ${{ matrix.arch }} == "aarch64" ]]; then
+            package_arch="arm64"
+          fi
+
+          mirror="http://ports.ubuntu.com/ubuntu-ports"
+          extra_sources=$(cat <<VAREOF
+          deb [arch=$package_arch] $mirror $dist main restricted
+          deb [arch=$package_arch] $mirror $dist-updates main restricted
+          deb [arch=$package_arch] $mirror $dist universe
+          deb [arch=$package_arch] $mirror $dist-updates universe
+          deb [arch=$package_arch] $mirror $dist multiverse
+          deb [arch=$package_arch] $mirror $dist-updates multiverse
+          deb [arch=$package_arch] $mirror $dist-backports main restricted universe multiverse
+          deb [arch=$package_arch] $mirror $dist-security main restricted
+          deb [arch=$package_arch] $mirror $dist-security universe
+          deb [arch=$package_arch] $mirror $dist-security multiverse
+          VAREOF
+          )
+
+          if [[ $package_arch != "amd64" ]]; then
+            # fix original sources
+            sudo sed -i -e "s#deb http#deb [arch=amd64] http#g" /etc/apt/sources.list
+
+            sudo dpkg --add-architecture $package_arch
+
+            echo "$extra_sources" | sudo tee -a /etc/apt/sources.list
+            echo "----"
+            sudo cat /etc/apt/sources.list
+          fi
+
           if [[ ${{ matrix.os_type }} == "linux" ]]; then
             sudo apt-get update -qq && sudo apt-get -y install \
               autoconf \
@@ -90,10 +148,11 @@ jobs:
               libfreetype6-dev \
               libgnutls28-dev \
               libmp3lame-dev \
+              libnuma-dev \
               libopus-dev \
               libsdl2-dev \
               libtool \
-              libva-dev \
+              libva-dev:$package_arch \
               libvdpau-dev \
               libvorbis-dev \
               libxcb1-dev \
@@ -127,6 +186,16 @@ jobs:
               yasm \
               xvid
           fi
+          echo "::endgroup::"
+
+          if [[ ${{ matrix.os_type }} == "linux" && ${{ matrix.arch }} == "aarch64" ]]; then
+            echo "::group::${{ matrix.os_type }}-${{ matrix.arch }} dependencies"
+            sudo apt-get -y install \
+              binutils-${{ matrix.host }} \
+              g++-${{ matrix.host }} \
+              gcc-${{ matrix.host }}
+            echo "::endgroup::"
+          fi
 
       - name: Setup Dependencies Windows
         if: ${{ matrix.os_type == 'windows' }}
@@ -154,6 +223,12 @@ jobs:
           echo "root_path=$PWD" >> $GITHUB_OUTPUT
           mkdir -p ./bin ./ffmpeg_build ./ffmpeg_sources
 
+      - name: Setup cross compilation
+        id: cross
+        if: ${{ matrix.arch == 'aarch64' }}
+        run: |
+          echo "CCPREFIX=/usr/bin/${{ matrix.host }}-" >> $GITHUB_OUTPUT
+
       - name: amf
         if: ${{ matrix.os_type != 'macos' }}
         # https://ffmpeg.org/general.html#AMD-AMF_002fVCE
@@ -164,31 +239,76 @@ jobs:
       - name: libx264
         env:
           root_path: ${{ steps.root.outputs.root_path }}
+          CCPREFIX: ${{ steps.cross.outputs.CCPREFIX }}
         working-directory: ffmpeg_sources/x264
         run: |
+          echo "::group::configure options"
+          ./configure --help || true  # this command has a non zero exit status, but we should continue anyway
+          echo "::endgroup::"
+
+          echo "::group::configure extra flags for cross compilation"
+          extra_configure=$(cat <<VAREOF
+          --host=${{ matrix.arch }}-${{ matrix.os_type }}
+          --cross-prefix=${CCPREFIX}
+          VAREOF
+          )
+          if [[ ${{ matrix.arch }} != "aarch64" ]]; then
+            extra_configure=""
+          fi
+          echo "$extra_configure"
+          echo "::endgroup::"
+
+          echo "::group::configure"
           PATH="$root_path/bin:$PATH" \
             PKG_CONFIG_PATH="$root_path/ffmpeg_build/lib/pkgconfig" \
             ./configure \
+            $extra_configure \
             --prefix="$root_path/ffmpeg_build" \
             --bindir="$root_path/bin" \
             --disable-cli \
             --enable-static
+          echo "::endgroup::"
+
+          echo "::group::make"
           PATH="$root_path/bin:$PATH" make -j$(nproc || sysctl -n hw.logicalcpu)
+          echo "::endgroup::"
+
+          echo "::group::make install"
           make install
+          echo "::endgroup::"
 
       - name: libx265
         env:
           root_path: ${{ steps.root.outputs.root_path }}
+          CCPREFIX: ${{ steps.cross.outputs.CCPREFIX }}
         working-directory: ffmpeg_sources/x265_git
         run: |
+          echo "::group::configure extra flags for cross compilation"
+          extra_configure="-DCMAKE_TOOLCHAIN_FILE=build/${{ matrix.arch }}-${{ matrix.os_type }}/crosscompile.cmake"
+
+          if [[ ${{ matrix.arch }} != "aarch64" ]]; then
+            # not currently supported in `aarch64`
+            extra_configure="-DENABLE_HDR10_PLUS=1"
+          fi
+          echo "$extra_configure"
+          echo "::endgroup::"
+
+          echo "::group::configure"
           PATH="$root_path/bin:$PATH" cmake -G "${{ matrix.cmake_generator }}" \
+            $extra_configure \
             -DCMAKE_INSTALL_PREFIX="$root_path/ffmpeg_build" \
             -DENABLE_CLI=off \
-            -DENABLE_HDR10_PLUS=1 \
             -DSTATIC_LINK_CRT=1 \
             ./source
+          echo "::endgroup::"
+
+          echo "::group::make"
           PATH="$root_path/bin:$PATH" make -j$(nproc || sysctl -n hw.logicalcpu)
+          echo "::endgroup::"
+
+          echo "::group::make install"
           make install
+          echo "::endgroup::"
 
       - name: nvenc
         id: nvenc
@@ -196,12 +316,17 @@ jobs:
         working-directory: ffmpeg_sources/nv-codec-headers
         # https://trac.ffmpeg.org/wiki/HWAccelIntro#NVENC
         run: |
+          echo "::group::make"
           make -j$(nproc || sysctl -n hw.logicalcpu)
+          echo "::endgroup::"
+
+          echo "::group::make install"
           if [[ ${{ matrix.os_type }} == "windows" ]]; then
             make install
           else
             sudo make install
           fi
+          echo "::endgroup::"
 
           echo "nvenc_path=$PWD" >> $GITHUB_OUTPUT
 
@@ -209,17 +334,38 @@ jobs:
         env:
           nvenc_path: ${{ steps.nvenc.outputs.nvenc_path }}
           root_path: ${{ steps.root.outputs.root_path }}
+          CCPREFIX: ${{ steps.cross.outputs.CCPREFIX }}
         working-directory: ffmpeg_sources/ffmpeg
         run: |
+          echo "::group::configure options"
+          ./configure --help || true  # this command has a non zero exit status, but we should continue anyway
+          echo "::endgroup::"
+
+          echo "::group::configure extra flags for cross compilation"
+          extra_configure=$(cat <<VAREOF
+          --arch=${{ matrix.arch }}
+          --cross-prefix=${CCPREFIX}
+          --enable-cross-compile
+          --target-os=${{ matrix.os_type }}
+          VAREOF
+          )
+          if [[ ${{ matrix.arch }} != "aarch64" ]]; then
+            extra_configure=""
+          fi
+          echo "$extra_configure"
+          echo "::endgroup::"
+
+          echo "::group::configure"
+          set +e  # do not fail
           PATH="$root_path/bin:$PATH" \
-            PKG_CONFIG_PATH="$nvenc_path:$root_path/ffmpeg_build/lib/pkgconfig" \
+            PKG_CONFIG_PATH="$nvenc_path:$root_path/ffmpeg_build/lib/pkgconfig:/usr/lib/${{ matrix.host }}/pkgconfig" \
             ./configure \
+            $extra_configure \
             --prefix="$root_path/ffmpeg_build" \
             --pkg-config-flags="--static" \
             --extra-cflags="-I$root_path/ffmpeg_build/include" \
             --extra-ldflags="-L$root_path/ffmpeg_build/lib" \
             --extra-libs="-lpthread -lm" \
-            --ld="g++" \
             --bindir="$root_path/bin" \
             --disable-all \
             --disable-autodetect \
@@ -232,15 +378,33 @@ jobs:
             --enable-static \
             --enable-swscale \
             --enable-version3 \
-            ${{ matrix.ffmpeg_extras }}
+            --pkg-config=pkg-config \
+            ${{ matrix.ffmpeg_extras }} \
+            || config_error=true
+          set -e  # reset fail on error
+          echo "::endgroup::"
+
+          echo "::group::config error log"
+          cat ./ffbuild/config.log
+
+          if [ $config_error ]
+          then
+            exit -1
+          fi
+          echo "::endgroup::"
+
+          echo "::group::make"
           PATH="$root_path/bin:$PATH" make -j$(nproc || sysctl -n hw.logicalcpu)
+          echo "::endgroup::"
+
+          echo "::group::make install"
           make install
-          hash -r
+          echo "::endgroup::"
 
       - name: Upload Artifacts
         uses: actions/upload-artifact@v3
         with:
-          name: ffmpeg-${{ matrix.os_type }}
+          name: ffmpeg-${{ matrix.os_type }}-${{ matrix.arch }}
           path: |
             ./ffmpeg_build/
 
@@ -252,15 +416,18 @@ jobs:
 
       - name: Prepare dependency branch
         run: |
-          # cleanup build
+          echo "::group::cleanup build"
           rm -f -r ./ffmpeg_build/share
           rm -f -r ./ffmpeg_build/lib/pkgconfig
+          echo "::endgroup::"
 
-          # empty contents
+          echo "::group::empty contents"
           rm -f -r ./ffmpeg-${{ matrix.os_type }}-${{ matrix.arch }}/*
+          echo "::endgroup::"
 
-          # copy build back to dependency branch
+          echo "::group::copy build back to dependency branch"
           cp -f -r ./ffmpeg_build/. ./ffmpeg-${{ matrix.os_type }}-${{ matrix.arch }}/
+          echo "::endgroup::"
 
       - name: Commit build
         if: ${{ github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') }}  # yamllint disable-line rule:line-length
