Update build-ffmpeg.yml

diff --git a/.github/workflows/build-ffmpeg.yml b/.github/workflows/build-ffmpeg.yml
--- a/.github/workflows/build-ffmpeg.yml
+++ b/.github/workflows/build-ffmpeg.yml
@@ -24,17 +24,17 @@ jobs:
             arch: x86_64
             shell: bash
             cmake_generator: Unix Makefiles
-            ffmpeg_extras: |
-              --enable-amf \
-              --enable-cuda \
-              --enable-cuda_llvm \
-              --enable-encoder=h264_amf,hevc_amf \
-              --enable-encoder=h264_nvenc,hevc_nvenc \
-              --enable-encoder=h264_vaapi,hevc_vaapi \
-              --enable-ffnvcodec \
-              --enable-nvenc \
-              --enable-v4l2_m2m \
-              --enable-vaapi \
+            ffmpeg_extras: >-
+              --enable-amf
+              --enable-cuda
+              --enable-cuda_llvm
+              --enable-encoder=h264_amf,hevc_amf
+              --enable-encoder=h264_nvenc,hevc_nvenc
+              --enable-encoder=h264_vaapi,hevc_vaapi
+              --enable-ffnvcodec
+              --enable-nvenc
+              --enable-v4l2_m2m
+              --enable-vaapi
               --enable-vdpau
           - os_type: linux
             os: ubuntu-22.04
@@ -42,40 +42,40 @@ jobs:
             shell: bash
             cmake_generator: Unix Makefiles
             host: aarch64-linux-gnu
-            ffmpeg_extras: |
-              --enable-amf \
-              --enable-cuda \
-              --enable-cuda_llvm \
-              --enable-encoder=h264_amf,hevc_amf \
-              --enable-encoder=h264_nvenc,hevc_nvenc \
-              --enable-encoder=h264_vaapi,hevc_vaapi \
-              --enable-ffnvcodec \
-              --enable-nvenc \
-              --enable-v4l2_m2m \
-              --enable-vaapi \
+            ffmpeg_extras: >-
+              --enable-amf
+              --enable-cuda
+              --enable-cuda_llvm
+              --enable-encoder=h264_amf,hevc_amf
+              --enable-encoder=h264_nvenc,hevc_nvenc
+              --enable-encoder=h264_vaapi,hevc_vaapi
+              --enable-ffnvcodec
+              --enable-nvenc
+              --enable-v4l2_m2m
+              --enable-vaapi
               --enable-vdpau
           - os_type: macos
             os: macos-11
             arch: x86_64
             shell: bash
             cmake_generator: Unix Makefiles  # should be `Xcode` but that fails
-            ffmpeg_extras: |
-              --enable-encoder=h264_videotoolbox,hevc_videotoolbox \
+            ffmpeg_extras: >-
+              --enable-encoder=h264_videotoolbox,hevc_videotoolbox
               --enable-videotoolbox
           - os_type: windows
             os: windows-2022
             arch: x86_64
             shell: msys2 {0}
             cmake_generator: MSYS Makefiles
-            ffmpeg_extras: |
-              --enable-amf \
-              --enable-cuda \
-              --enable-d3d11va \
-              --enable-encoder=h264_amf,hevc_amf \
-              --enable-encoder=h264_mf,hevc_mf \
-              --enable-encoder=h264_nvenc,hevc_nvenc \
-              --enable-ffnvcodec \
-              --enable-nvenc \
+            ffmpeg_extras: >-
+              --enable-amf
+              --enable-cuda
+              --enable-d3d11va
+              --enable-encoder=h264_amf,hevc_amf
+              --enable-encoder=h264_mf,hevc_mf
+              --enable-encoder=h264_nvenc,hevc_nvenc
+              --enable-ffnvcodec
+              --enable-nvenc
               --enable-mediafoundation
     runs-on: ${{ matrix.os }}
     defaults:
@@ -314,6 +314,7 @@ jobs:
           echo "::endgroup::"
 
           echo "::group::configure"
+          set +e  # do not fail
           PATH="$root_path/bin:$PATH" \
             PKG_CONFIG_PATH="$nvenc_path:$root_path/ffmpeg_build/lib/pkgconfig" \
             ./configure \
@@ -335,7 +336,9 @@ jobs:
             --enable-static \
             --enable-swscale \
             --enable-version3 \
-            ${{ matrix.ffmpeg_extras }} || config_error=true
+            ${{ matrix.ffmpeg_extras }} \
+            || config_error=true
+          set -e  # reset fail on error
 
           # temp disabled
           # --ar="${CCPREFIX}ar" \
