Setup GITHUB_ENV before starting the VM

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -420,6 +420,41 @@ jobs:
           echo "PROCESSOR_COUNT=${PROCESSOR_COUNT}" >> "${GITHUB_OUTPUT}"
           echo "PROCESSOR_COUNT: ${PROCESSOR_COUNT}"
 
+      - name: Setup ENV
+        id: root
+        shell: bash
+        run: |
+          set -e
+          cd "$GITHUB_WORKSPACE"
+          echo "ROOT_PATH=$PWD" >> "${GITHUB_ENV}"
+
+          MAKE_CMD="make"
+          if [ "${{ startsWith(matrix.shell, 'freebsd') }}" = true ]; then
+            # use gmake on FreeBSD instead of make
+            MAKE_CMD="gmake"
+          fi
+          echo "MAKE_CMD=${MAKE_CMD}" >> "${GITHUB_ENV}"
+
+      - name: Setup cross compilation
+        id: cross
+        if: matrix.target != ''
+        shell: bash
+        run: |
+          set -e
+          cd "$GITHUB_WORKSPACE"
+          TOOLCHAIN=${{ env.ROOT_PATH }}/cmake/toolchains/${{ matrix.target }}.cmake
+
+          # fail if file does not exist
+          if [ ! -f $TOOLCHAIN ]; then
+              echo "Toolchain file not found: $TOOLCHAIN"
+              exit 1
+          fi
+
+          echo "CMAKE_TOOLCHAIN_FILE=$TOOLCHAIN" >> "${GITHUB_ENV}"
+          if [[ ${{ runner.os }} == 'Linux' ]]; then
+            echo "CCPREFIX=/usr/bin/${{ matrix.target }}-" >> "${GITHUB_ENV}"
+          fi
+
       - name: Setup FreeBSD
         if: startsWith(matrix.shell, 'freebsd')
         uses: vmactions/freebsd-vm@c54ba3b62f49de9b67a2f3af017ab6152f0ebb6f  # v1.3.4
@@ -460,39 +495,6 @@ jobs:
           run: |
             git config --global --add safe.directory "*"
           sync: rsync
-
-      - name: Setup ENV
-        id: root
-        run: |
-          set -e
-          cd $GITHUB_WORKSPACE
-          echo "ROOT_PATH=$PWD" >> "${GITHUB_ENV}"
-
-          MAKE_CMD="make"
-          if [ "${{ startsWith(matrix.shell, 'freebsd') }}" = true ]; then
-            # use gmake on FreeBSD instead of make
-            MAKE_CMD="gmake"
-          fi
-          echo "MAKE_CMD=${MAKE_CMD}" >> "${GITHUB_ENV}"
-
-      - name: Setup cross compilation
-        id: cross
-        if: matrix.target != ''
-        run: |
-          set -e
-          cd $GITHUB_WORKSPACE
-          TOOLCHAIN=${{ env.ROOT_PATH }}/cmake/toolchains/${{ matrix.target }}.cmake
-
-          # fail if file does not exist
-          if [ ! -f $TOOLCHAIN ]; then
-              echo "Toolchain file not found: $TOOLCHAIN"
-              exit 1
-          fi
-
-          echo "CMAKE_TOOLCHAIN_FILE=$TOOLCHAIN" >> "${GITHUB_ENV}"
-          if [[ ${{ runner.os }} == 'Linux' ]]; then
-            echo "CCPREFIX=/usr/bin/${{ matrix.target }}-" >> "${GITHUB_ENV}"
-          fi
 
       - name: Configure
         run: |
